apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: npita1/edrogerija-eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: mysql-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: http
  type: ClusterIP