apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cart-db
spec:
  serviceName: "cart-db"
  replicas: 1
  selector:
    matchLabels:
      app: cart-db
  template:
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: cart_db
          volumeMounts:
            - name: cart-db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: cart-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: cart-db
  clusterIP: None