apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: cm9vdA==             
  MYSQL_PASSWORD: cGFzc3dvcmQ=     
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODY2RTMyNzIzNTc1Mzg3ODJGNEMzRjQ0Mjg0NzJCNELIarwGNTBGNjQ1MzY3NTY2QjU5NzA=